//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatingSignupWithlogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage ="First Name is Required")]
        public string FirstName { get; set; }
        
        [DisplayName("Last Name")]
        [Required(ErrorMessage ="Last name is Required")]
        public string LastName { get; set; }
        
        [DisplayName("Gender")]
        [Required(ErrorMessage ="Gender is Required")]
        public string gender { get; set; }
        
        [DisplayName("Age")]
        [Required(ErrorMessage ="Age is Required")]
        public int age { get; set; }
        
        [DisplayName("Email")]
        [Required(ErrorMessage ="Email is Required")]
        public string email { get; set; }
        
        [DisplayName("Password")]
        [Required(ErrorMessage ="Password is Required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is Required")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Password is not match")]
        public string confirmPassword { get; set; }
    }
}
